spring:
  application:
    name: SocksTask
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socks_db
    username: postgres
    password: 123
  liquibase:
    change-log: db/changelog/changelog.yaml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
server:
  port: 8080